services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  db_dev:
    image: postgres:latest
    environment:
      POSTGRES_HOST: db_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marketplace_db_dev
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  mongo_dev:
    image: mongo:latest
    container_name: mongo_dev
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27018:27017"
    volumes:
      - mongo_data_dev:/data/db
    networks:
      - app_network

  app:
    build: .
    depends_on:
      - db
      - db_dev
      - mongo
      - mongo_dev
    environment:
      DB_HOST: db  # For prod
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: marketplace_db
      DB_PORT: 5432
      DB_DEV_HOST: db_dev  # For dev DB
      DB_DEV_NAME: marketplace_db_dev
      DB_DEV_PORT: 5432
      MONGO_HOST: mongo  # For prod
      MONGO_PORT: 27017
      MONGO_CLUSTER: cluster0.fpei0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      MONGO_USER: catmepentest
      MONGO_PASSWORD: PgmIFPs2KynmkStD
      MONGO_DEV_HOST: mongo_dev  # For dev
      MONGO_DEV_PORT: 27017
    volumes:
      - .:/app
    command: sh -c "./build.sh"
    ports:
      - "7676:7676"
    networks:
      - app_network

volumes:
  postgres_data:
  postgres_data_dev:
  mongo_data:
  mongo_data_dev:

networks:
  app_network:
    driver: bridge
